version: "3.9"

networks:
  my_network:
    driver: bridge

services:
  inventory-back:
    container_name: inventory-back
    build:
      context: .
      dockerfile: cmd/Dockerfile
    environment:
      DATABASE_URL: "host=localhost user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - inventory_db
    networks:
      - my_network
    env_file:
      - cmd/.env
  inventory_db:
    container_name: inventory_db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - my_network
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
